name: Build & Push Image
on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'The image tag'
        required: false
        default: '2025-latest'

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ''
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd

      - name: Login to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.PAT }}

      - name: Build
        shell: bash
        run: docker buildx build -t ${{ vars.IMG_NAME }}:${{ github.event.inputs.image-tag }} --load .

      - name: Push
        shell: bash
        run: |
          docker tag ${{ vars.IMG_NAME }}:${{ github.event.inputs.image-tag }} ${{ vars.USERNAME }}/${{ vars.IMG_NAME }}:${{ github.event.inputs.image-tag }}
          docker push ${{ vars.USERNAME }}/${{ vars.IMG_NAME }}:${{ github.event.inputs.image-tag }}
